[book]
authors = ["IrishBruse"]
language = "en"
multilingual = false
src = "src"
title = "LDtkMonogame"
description = "The LDtkMonogame nuget documentation"

[build]
build-dir = "../../IrishBruse.github.io/ldtk/"
use-default-preprocessors = true
create-missing = false

[output.html.print]
enable = false

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0        # the depth to start folding

[output.html]
theme = "theme"
default-theme = "ldtk"
preferred-dark-theme = "ldtk"
curly-quotes = false
mathjax-support = false
copy-fonts = true
no-section-label = true
additional-js = []
git-repository-url = "https://github.com/IrishBruse/LDtkMonogame"
edit-url-template = "https://github.com/IrishBruse/LDtkMonogame/edit/main/Documentation/{path}"
discord-url = "https://ldtk.io/go/discord"
