name: Build Examples

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: Restore dependencies
        run: dotnet restore
      - name: Content Extension dll
        run: dotnet build LDtkMonogame.ContentPipeline/LDtkMonogame.ContentPipeline.csproj -f netcoreapp3.1
      - name: Api
        run: dotnet build LDtkMonogame.Examples/Api/Api.csproj --no-restore -f netcoreapp3.1
      - name: Platformer
        run: dotnet build LDtkMonogame.Examples/Platformer/Platformer.csproj --no-restore -f netcoreapp3.1
      - name: Quickstart
        run: dotnet build LDtkMonogame.Examples/Quickstart/Quickstart.csproj --no-restore -f netcoreapp3.1
