name: Pull Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Install tools
        run: dotnet tool restore

      - name: Build ContentPipeline
        run: dotnet build --configuration Release --no-restore ${{github.workspace}}/LDtk.ContentPipeline/LDtk.ContentPipeline.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
